### ISSUE TITLE
Add maxSize option for output files

### ISSUE THREAD

**Issue by benatwork99** [gabrysbiz/css-splitter-maven-plugin#2]
This discussion: 

http://stackoverflow.com/a/11080846/1666041
https://gist.github.com/psebborn/1885511#gistcomment-1383451

talks about there being a maximum file size for IE9 independent of the number of selectors. An optional maxSize setting, where if a file got that large it was split into a new file OR if a file got the maximum number of selectors it was split into a new file, would be neat.

**Comment by agabrys** [comment]
It will be really hard to split files depending on the file size (without reading-creating-saving files loop) , because it depends on used:
* encoding
* CSS code compression (see [Minify Maven Plugin](http://samaxes.github.io/minify-maven-plugin/))

I think this is also a rarely problem, so maybe it is easier to split depending on rules with lower max quantity.

You can read more about splitting over selector here: #1
